package:
  name: narupa-mdanalysis
  version: {{ NARUPA_BUILD_VERSION }}

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.6.0
    - setuptools

  run:
    - python >=3.6.0
    - narupa-core =={{ NARUPA_BUILD_VERSION }}
    - numpy

about:
  home: https://narupa.readthedocs.io
  license: GPL-3
  license_file: {{ NARUPA_LICENSE_PATH }}
  summary: Rosetta interface methods for Narupa.
  description: |
    Narupa is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides methods for communication between
    Rosetta and Narupa.
  doc_url: https://narupa.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/narupa-protocol